CREATE USER 'mysqlcoursesuser'@'localhost' IDENTIFIED BY 'Ed61a57pe13XA88j';
GRANT USAGE ON *.* TO 'mysqlcoursesuser'@'localhost';
GRANT SELECT, EXECUTE, SHOW VIEW, ALTER, ALTER ROUTINE, CREATE, CREATE ROUTINE, CREATE TEMPORARY TABLES, CREATE VIEW, DELETE, DROP, EVENT, INDEX, INSERT, REFERENCES, TRIGGER, UPDATE, LOCK TABLES  ON `sfts\_courses`.* TO 'mysqlcoursesuser'@'localhost';
FLUSH PRIVILEGES;